## Практическая работа

В этой практической работе пять обязательных задач.

*Обязательные задачи* помогут проверить, что вы действительно усвоили материал модуля. Сдайте их на проверку.

Удачи!

Цели практической работы: 


1.   Потренироваться в обучении модели линейной регрессии.
2.   Потренироваться в обучении модели логистической регрессии. 
3.   Потренироваться в обучении модели многослойного персептрона.





Что оценивается:

*   Все пункты и критерии приёмки по каждому заданию выполнены.
*   Код оформлен и работает корректно.





Как отправить работу на проверку:

Сдайте практическую работу этого модуля через систему контроля версий Git сервиса Skillbox GitLab. После загрузки работы на проверку напишите об этом в личном кабинете своему куратору.

В этом задании вам нужно построить модель классификации, определяющую категорию цены/цену подержанного автомобиля в зависимости от характеристик транспортного средства. 

Мы будем использовать датасет из коллекции подержанных автомобилей, выставленных на продажу в Соединенных Штатах. Он уже подготовлен, без выбросов и с категориальными фичами, преобразованными с помощью one hot encoding, и количественными фичами, стандартизированными с помощью скейлеров.


### Описание датасета:
- `id`: идентификатор записи;
- `is_manufacturer_name`: признак производителя автомобиля;

- `region_*`: регион;
- `x0_*`: тип топлива;
- `manufacturer_*`: производитель;
- `short_model_*`: сокращённая модель автомобиля;
- `title_status_*`: статус;
- `transmission_*`: коробка передач;
- `state_*`: штат;
- `age_category_*`: возрастная категория автомобиля;

- `std_scaled_odometer`: количество пройденных миль (после стандартизации);
- `year_std`: год выпуска (после стандартизации);
- `lat_std`: широта (после стандартизации);
- `long_std`: долгота (после стандартизации);
- `odometer/price_std`: отношение стоимости к пробегу автомобиля (после стандартизации);
- `desc_len_std`: количество символов в тексте объявления о продаже (после стандартизации);
- `model_in_desc_std`: количество наименований модели автомобиля в тексте объявления о продаже (после стандартизации);
- `model_len_std`: длина наименования автомобиля (после стандартизации);
- `model_word_count_std`: количество слов в наименовании автомобиля (после стандартизации);
- `month_std`: номер месяца размещения объявления о продаже автомобиля (после стандартизации);
- `dayofweek_std`: день недели размещения объявления о продаже автомобиля (после стандартизации);
- `diff_years_std`: количество лет между годом производства автомобиля и годом размещения объявления о продаже автомобиля (после стандартизации);

- `price`: стоимость;
- `price_category`: категория цены.

## Обязательные задачи

In [410]:
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, mean_absolute_error
from sklearn.model_selection import train_test_split 
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier

In [159]:
df = pd.read_csv('vehicles_dataset_prepared.csv')
df.head()

id  price price_category  is_audi  is_ford  is_chevrolet  \
0  7308295377  54990           high        0        0             0   
1  7316380095  16942         medium        0        1             0   
2  7313733749  35590           high        0        0             0   
3  7308210929  14500         medium        0        0             0   
4  7303797340  14590         medium        0        0             0   

   is_toyota  x0_diesel  x0_electric  x0_gas  ...  long_std  year_std  \
0          0        1.0          0.0     0.0  ...  0.484245  1.322394   
1          0        0.0          0.0     0.0  ...  1.110800  0.695973   
2          0        0.0          0.0     1.0  ...  0.531185  0.852578   
3          1        0.0          0.0     1.0  ...  0.853562  0.226157   
4          0        0.0          0.0     0.0  ...  0.557607  0.069552   

   odometer/price_std  desc_len_std  model_in_desc_std  model_len_std  \
0           -0.510784      0.632075          -0.155788       1.163032   
1           -0.402947     -0.646781          -0.155788       0.932087   
2           -0.514480      0.560744          -0.155788       0.470197   
3           -0.241883      0.180435          -0.155788      -0.915473   
4           -0.333074      0.766366          -0.155788       1.163032   

   model_word_count_std  month_std  dayofweek_std  diff_years_std  
0              1.910669  -0.615846       1.120284       -1.322394  
1              1.235799   1.623784      -1.374972       -0.695973  
2              0.560930  -0.615846      -0.376870       -0.852578  
3             -0.788810  -0.615846       1.120284       -0.226157  
4              1.910669  -0.615846       0.122182       -0.069552  

[5 rows x 1463 columns]

**Задача 0. Линейная регрессия**

Вспомните задачу по предсказанию стоимости поддержанного автомобиля. Попробуем обучить модель линейной регрессии для предсказания цены автомобиля (колонка `price`). Для этого проделайте следующие шаги:

- Подготовьте данные: удалите колонки, которые косвенно содержат информацию о целевой переменной (`odometer/price_std`, `price_category`).
- Разделите выборку на треин и тест в отношении 70/30.
- Обучите модель линейной регрессии с дефолтными параметрами.
- Посчитайте значение метрики mae на тестовой выборке для линейной регрессии.
- Выведите получившиеся коэффициенты линейной регрессии при каждом параметре обучающей выборки с помощью метода `coef_`. Есть ли коэффициенты, которые равны нулю? Если есть, выведите названия фичей с нулевым коэффициентом
- Удалите фичи, коэффициенты которых равны нулю. И переобучите модель. Убедитесь, что значение метрики не изменилось.



In [418]:
# Ваш код здесь
df_prepared = df.copy()
df_prepared = df_prepared.drop(['price_category', 'odometer/price_std'], axis=1)

train, test = train_test_split(df_prepared, test_size=0.3, random_state=42)

lr = LinearRegression()


lr.fit(train.drop(['price'], axis=1), train.price)
pred = lr.predict(test.drop(['price'], axis=1))
mean_absolute_error(test.price, pred)

4600.341116688055

In [162]:
lr.coef_[(lr.coef_ == 0)]

array([0.])

In [163]:
coefficients = lr.coef_

coef_df = pd.DataFrame({'Feature': train.drop(['price'], axis=1).columns, 'Coefficient': coefficients})

print(coef_df)

zero_coef_features = coef_df[coef_df['Coefficient'] == 0]['Feature'].to_list()

print(coef_df[coef_df['Coefficient'] == 0])

                   Feature  Coefficient
0                       id     0.000006
1                  is_audi   254.298335
2                  is_ford  1073.909874
3             is_chevrolet  -184.763046
4                is_toyota   471.497983
...                    ...          ...
1455         model_len_std    25.182236
1456  model_word_count_std   643.950550
1457             month_std  -166.691604
1458         dayofweek_std    23.050436
1459        diff_years_std -2803.980404

[1460 rows x 2 columns]
                   Feature  Coefficient
1360  manufacturer_ferrari          0.0


In [175]:
train1 = train.drop(columns=zero_coef_features)
test1 = test.drop(columns=zero_coef_features)


lr.fit(train1.drop(['price'], axis=1), train1.price)
pred1 = lr.predict(test1.drop(['price'], axis=1))
mean_absolute_error(test1.price, pred1)

4600.341118668767

**Задача 1. Логистическая регрессия**

Теперь в рамках тех же данных попробуйте предсказать `price_category` с помощью алгоритма логистической регрессии. Предварительно из датафрейма удалите переменные, в которых косвенно содержится информация о целевой переменной (`odometer/price_std`, `price`). 

Для обученной модели нужно:

- рассчитать и вывести метрику качества (accuracy) на тренировочной выборке;
- сделать предикт на тестовых данных и положить его в переменную `logreg_pred`;
- рассчитать и вывести accuracy и confusion_matrix на тестовой выборке.


Задание засчитывается, если: 
- accuracy на тренировочной выборке > 87%;
- accuracy на тестовой выборке > 75.5%.

Для улучшения метрики можно преобразовывать входные данные, тюнить параметры логистической регрессии.

In [362]:
# Ваш код подготовки данных здесь. Допишите инициализацию входных фичей и целевую переменную
df_prepared1 = df.copy()
df_prepared1 = df_prepared1.drop(['price', 'odometer/price_std', 'id'], axis=1)

x = df_prepared1.drop(['price_category'], axis=1)
y = df_prepared1.price_category

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
logreg = LogisticRegression(random_state=42, penalty='l2', solver='saga')

In [364]:
from sklearn.preprocessing import StandardScaler

# Масштабирование данных
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [365]:
# Ваш код обучения моделей здесь
logreg.fit(X_train_scaled, y_train)

logreg_pred = logreg.predict(X_test_scaled)

y_train_pred = logreg.predict(X_train_scaled)

print(f'Accuracy на тестовой выборке: {accuracy_score(y_test, logreg_pred)}')
print(f'Accuracy на тренировочной выборке: {accuracy_score(y_train, y_train_pred)}')
print(f'''Случайный лес:
{confusion_matrix(y_test, logreg_pred)}''')

Accuracy на тестовой выборке: 0.7572765072765073
Accuracy на тренировочной выборке: 0.8834307992202729
Случайный лес:
[[530  21 115]
 [ 12 521 101]
 [106 112 406]]


C:\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


**Задача 2. Многослойный персептрон**

Решите задачу, поставленную в предыдущем задании, применив модель многослойного персептрона. Добейтесь лучших значений точности на тренировочной и тестовой выборках, чем на логистической регрессии, с помощью данного алгоритма. 

Значимым увеличением точности в данном задании будем считать увеличение больше, чем на 0.01 по метрике accuracy.

In [368]:
# Ваш код здесь
mlp = MLPClassifier(random_state=42, max_iter=500, hidden_layer_sizes=(100,50))
mlp.fit(X_train_scaled, y_train)

pred_mlp = mlp.predict(X_test_scaled)
y_train_pred_mlp = mlp.predict(X_train_scaled)

print(f'Accuracy на тестовой выборке: {accuracy_score(y_test, pred_mlp)}')
print(f'Accuracy на тренировочной выборке: {accuracy_score(y_train, y_train_pred_mlp)}')

Accuracy на тестовой выборке: 0.7603950103950103
Accuracy на тренировочной выборке: 0.9977907732293697


**Задача 3. Сравнение с древовидными моделями**

Обучите модель случайного леса на тех же данных для предсказания `price_category`. Сравните качество с моделью логистической регрессии и многослойного персептрона. Словами опишите, какая из моделей в каких случаях работает лучше по результатам на тестовой выборке, и обоснуйте свой выбор.

In [370]:
# Логистическая регрессия: Лучше всего работает на линейно разделимых данных. Если данные сложные, точность будет низкой.
# Случайный лес: Хорошо работает на данных с нелинейными зависимостями. Устойчив к переобучению и не требует масштабирования.
# Многослойный персептрон: Мощная модель для сложных данных, но требует тщательной настройки и масштабирования.
# Лучше всего с нашими данными справилась модель RF, accuracy score самый высокий

In [412]:
# Ваш код здесь
clf_rf = RandomForestClassifier(random_state=42)
clf_rf.fit(X_train_scaled, y_train)

predicted_train = clf_rf.predict(X_train_scaled)
predicted_test = clf_rf.predict(X_test_scaled)

print(accuracy_score(y_train, predicted_train))
print(accuracy_score(y_test, predicted_test))

1.0
0.7692307692307693


**Задача 4. Стратегия голосования**

Реализуйте стратегию голосования для предсказания целевой переменной.
Голосование в задаче классификации — это когда несколько моделей выдают свои предикты, и финальным выбирается тот предикт, который предсказали большинство моделей.

Для реализации этой стратегии проделайте следующее:

- сохраните предсказания каждой из моделей (случайный лес, многослойный персептрон, логистическая регрессия) для тестовой выборки в датафрейм `pred_df`;
- в четвертую колонку `target` положите тот класс, который предсказало большинство классификаторов. Например, если в строке были значения `high, medium, medium`, в `target` нужно положить `medium`.

     Если в строке три разных класса — `high, medium, low`, — придумайте свою стратегию по выбору значения. Самая простая стратегия: выбрать рандомно одно значение из трёх.

- посчитайте точность предсказания с помощью голосования. Выведите значения метрик accuracy и confusion_matrix.


Добейтесь значения точности > 78% 

In [414]:
# Ваш код здесь
logreg1 = LogisticRegression(random_state=42, penalty='l1', solver='saga')
logreg1.fit(X_train_scaled, y_train)

mlp1 = MLPClassifier(random_state=42, max_iter=500, hidden_layer_sizes=(100,50))
mlp1.fit(X_train_scaled, y_train)

clf_rf = RandomForestClassifier(random_state=42)
clf_rf.fit(X_train_scaled, y_train)

predicted_test1 = clf_rf.predict(X_test_scaled)
pred_mlp1 = mlp1.predict(X_test_scaled)
logreg_pred1 = logreg1.predict(X_test_scaled)

import numpy as np
def voting(row):
    counts = row.value_counts()
    if counts.max() > 1:
        return counts.idxmax()
    else:
        return np.random.choice(row)
        
pred_df = pd.DataFrame({'LogReg': logreg_pred1, 'MLP': pred_mlp1, 'RF' : predicted_test1})
pred_df['target'] = pred_df.apply(voting, axis=1)

print(f'Accuracy с голосованием: {accuracy_score(y_test, pred_df['target'])}')
print(confusion_matrix(y_test, pred_df['target']))

C:\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


Accuracy с голосованием: 0.7822245322245323
[[546  19 101]
 [  9 544  81]
 [ 97 112 415]]


**Примечание:**

В этом домашнем задании в задаче номер 1 и далее перед вами встал выбор: включать ли в обучение колонку `id`. При удалении данной колонки во время обучении логистической регрессии качество заметно улучшается.

Вообще обучать любую модель (будь то логистическая или линейная регрессия, или древовидный алгоритм) на данных айдишников не считается хорошей практикой. Как правило, между `id` и целевой переменной не должно быть никаких взаимосвязей. Включая колонку `id` в качества атрибута в обучение, вы стараетесь "заточить" результаты своей модели под айдишники записей. Таким образом модель обучится на некотором наборе "частных случаев", и, возможно, не обратит внимание на общие зависимости.   